# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5c79d467afacab0d6fb34429bb4d6f81385d9e3237986bbc9eb1e1f6c5c08bcf4b2f08a9e36270e6231afacfa703a6f7c0c78cf5a007449920fa36f0826d86a

test:
  secret_key_base: 41cccc72e0c694bd31492664dbd3731214026bbfb28d6cd943aeba6d593b9b99878aaa84efb48c9c37d00faa4e0b9b49e2b6127c66c94a15f899128fc69698ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
